# Generated by Django 2.1.5 on 2019-09-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_auto_20190909_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='subcategory',
            field=models.CharField(default='', max_length=100),
        ),
    ]
